//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemo5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_info
    {
        public int id { get; set; }
        public string names { get; set; }
        public int mobile { get; set; }
    }
}
